---
  - hosts: vmware
    remote_user: birth
    become: yes
    tasks:
      - name: Cria uma maquina virtual no host ESXi
        vmware_guest:
          hostname: 192.168.126.139
          username: root
          password: VMware6.7
          validate_certs: no
          folder: /
          name: VM_Wordpress_server
          state: poweredoff
          guest_id: centos64Guest
#          esxi_hostname: 192.168.162.139
          disk:
            - size_gb: 10
              type: thin
              datastore: Datastore-WordPress
          hardware:
            memory_mb: 512
            num_cpus: 1
            scsi: paravirtual
          networks:
            - name: VM Network
              device_type: vmxnet3
        delegate_to: localhost
        register: deploy_vm
      - name: Cria uma maquina virtual no host ESXi no storage 2
        vmware_guest:
          hostname: 192.168.126.139
          username: root
          password: VMware6.7
          validate_certs: no
          folder: /
          name: VM_Banco_server
          state: poweredoff
          guest_id: centos64Guest
#          esxi_hostname: 192.168.162.139
          disk:
            - size_gb: 10
              type: thin
              datastore: Datastore-Banco
          hardware:
            memory_mb: 512
            num_cpus: 1
            scsi: paravirtual
          networks:
            - name: VM Network
              device_type: vmxnet3
        delegate_to: localhost
        register: deploy_vm 
